version: "3.7"
services:
    app:
        build:
            args:
                user: rafael
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: opengrades
        container_name: ${APP_NAME}-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - opengrades
    db:
        image: mysql:8.0
        container_name: ${APP_NAME}-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
            MYSQL_ROOT_HOST: "%"
        ports:
            - "${DB_EXTERNAL_PORT}:3306"
        networks:
            - opengrades

    nginx:
        image: nginx:1.17-alpine
        container_name: ${APP_NAME}-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - opengrades

    redis:
        image: redis:alpine
        container_name: ${APP_NAME}-redis
        restart: unless-stopped
        command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
        volumes:
            - ./docker-compose/redis:/data
        ports:
            - "8002:6379"
networks:
    opengrades:
        driver: bridge
